services:
  email-assistant-backend:
    build: ./email-writer-sb
    ports:
      - "8080:8080"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      CLIENT_KEY: email-extension-dev
    restart: unless-stopped

  frontend:
    build: ./email-writer-frontend
    ports:
      - "3000:80"
    depends_on:
      - email-assistant-backend
    restart: unless-stopped
